package views;

import javax.swing.JButton;
import javax.swing.JMenu;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import controller.Controller;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class VentanaMain extends javax.swing.JFrame {
    private Controller controller;

    /**
     * Creates new form VentanaEditar
     */
    public VentanaMain() {
        this.setVisible(true);
        initComponents();
        this.setTitle("JavaReunion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jMenu2 = new javax.swing.JMenu();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        jLabelPrincipal = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuAgregar = new javax.swing.JMenu();
        menuEditar = new javax.swing.JMenu();
        menuEliminar = new javax.swing.JMenu();
        menuMostrar = new javax.swing.JMenu();
        menuMostrarTipo = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuFile = new javax.swing.JMenu();
        menuCargar = new javax.swing.JMenu();
        menuExtraer = new javax.swing.JMenu();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelPrincipal.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabelPrincipal.setText("Bienvenido a ReunionManager3.0");

        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jMenuBar1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jMenuBar1ComponentAdded(evt);
            }
        });

        menuMenu.setText("Menu");

        menuAgregar.setText("Agregar");
        menuAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAgregarMouseClicked(evt);
            }
        });
        menuMenu.add(menuAgregar);

        menuEditar.setText("Editar");
        menuEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditarMouseClicked(evt);
            }
        });
        menuMenu.add(menuEditar);

        menuEliminar.setText("Eliminar");
        menuEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEliminarMouseClicked(evt);
            }
        });
        menuMenu.add(menuEliminar);

        menuMostrar.setText("Mostrar Reuniones");
        menuMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMostrarMouseClicked(evt);
            }
        });
        menuMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMostrarActionPerformed(evt);
            }
        });
        menuMenu.add(menuMostrar);

        menuMostrarTipo.setText("Mostar Tipo");
        menuMostrarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMostrarTipoMouseClicked(evt);
            }
        });
        menuMenu.add(menuMostrarTipo);

        jMenuBar1.add(menuMenu);
        jMenuBar1.add(jMenu3);

        menuFile.setText("File");

        menuCargar.setText("Carga");
        menuCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCargarMouseClicked(evt);
            }
        });
        menuFile.add(menuCargar);

        menuExtraer.setText("Extraer");
        menuExtraer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExtraerMouseClicked(evt);
            }
        });
        menuFile.add(menuExtraer);

        jMenuBar1.add(menuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir))
                .addGap(1, 1, 1)
                .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        


    public void setController(Controller controller)
  {
    this.controller = controller;
  }

    private void jMenuBar1ComponentAdded(java.awt.event.ContainerEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {                                             

    }                                            

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {                                          
       System.exit(0);
    }                                         

    private void menuMostrarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void menuMostrarMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        VentanaMostrar mostrar = new VentanaMostrar();
        mostrar.setVisible(true);
    }                                        

    private void menuAgregarMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        VentanaAgregar agregar = new VentanaAgregar();
        agregar.setVisible(true);
    }                                        

    private void menuEditarMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        VentanaEditar editar = new VentanaEditar();
        editar.setVisible(true);  
    }                                       

    private void menuEliminarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        VentanaEliminar eliminar = new VentanaEliminar();
        eliminar.setVisible(true);
    }                                         

    private void menuMostrarTipoMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        VentanaMostrarTipo mostrarTipo = new VentanaMostrarTipo();
        mostrarTipo.setVisible(true);
    }                                            

    private void menuExtraerMouseClicked(java.awt.event.MouseEvent evt) {                                         
        try {
            // TODO add your handling code here:
            controller.exportarCSV();
        } catch (IOException ex) {
            Logger.getLogger(VentanaMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void menuCargarMouseClicked(java.awt.event.MouseEvent evt) {                                        
        try {
            // TODO add your handling code here:
        controller.inicializarDatos();
        } catch (IOException ex) {
            Logger.getLogger(VentanaMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                       


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabelPrincipal;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAgregar;
    private javax.swing.JMenu menuCargar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuEliminar;
    private javax.swing.JMenu menuExtraer;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuMostrar;
    private javax.swing.JMenu menuMostrarTipo;
    // End of variables declaration                   

}
